# Generated by Django 4.2 on 2023-04-10 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_password_user_contraseña_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='Contraseña',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='Nombre de usuario',
            new_name='username',
        ),
    ]
