# Generated by Django 4.2 on 2023-04-20 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_friends'),
    ]

    operations = [
        migrations.AddField(
            model_name='friends',
            name='name_save',
            field=models.TextField(default=''),
        ),
    ]
