# Generated by Django 4.2 on 2023-04-20 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_friends_name_save'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friends',
            name='name_save',
            field=models.CharField(max_length=100),
        ),
    ]
